import math
import datetime

CONFIDENCE = 0.95
ALPHA = 1 - CONFIDENCE
LTS_TOTAL_TIME = 30
# CONFIGURATION = (LTS_TOTAL_TIME)//2
CONFIGURATION = 4
CONFIGURATION_STEP = 1
RUNS = 2
STEP = 50000
WARM_UP = 10000
NAME = f"results/{datetime.datetime.now().strftime('%Y%m%d_%H%M')}"
SEMAPHORES = 4
# PERMUTATIONS = math.factorial(SEMAPHORES)//2
PERMUTATIONS = 1
