import math
import datetime

CONFIDENCE = 0.95
ALPHA = 1 - CONFIDENCE
TLS_TOTAL_TIME = 30
CONFIGURATION = (TLS_TOTAL_TIME)//2
# CONFIGURATION = 4
TANGENTIAL_FLOW = 0.3
ROU_PATH = "lightSync.rou.xml"
CONFIGURATION_STEP = 1
RUNS = 10
STEP = 50000
WARM_UP = 10000
NAME = f"results/results_t15/03/"
SEMAPHORES = 4
